export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  team: '/teams',
  teamDetail: '/teams/:teamId',
  projects: '/projects',
  projectNew: '/projects/new',
  project: '/projects/:projectId',
  projectBoard: '/projects/:projectId/board',
  projectMembers: '/projects/:projectId/members',
  projectEdit: '/projects/:projectId/edit',
  projectActivity: '/projects/:projectId/activity',
  projectSettings: '/projects/:projectId/settings',
  kanban: '/projects/:projectId/kanban',
  kanbanList: '/kanban',
}

export const routePaths = {
  login: () => ROUTES.login,
  signup: () => ROUTES.signup,
  dashboard: () => ROUTES.dashboard,
  team: () => '/teams',
  teamDetail: (teamId) => `/teams/${teamId}`,
  projects: () => ROUTES.projects,
  projectNew: () => ROUTES.projectNew,
  project: (projectId) => `/projects/${projectId}`,
  projectBoard: (projectId) => `/projects/${projectId}/board`,
  projectMembers: (projectId) => `/projects/${projectId}/members`,
  projectEdit: (projectId) => `/projects/${projectId}/edit`,
  projectActivity: (projectId) => `/projects/${projectId}/activity`,
  projectSettings: (projectId) => `/projects/${projectId}/settings`,
  kanban: (projectId) => `/projects/${projectId}/kanban`,
  kanbanList: () => '/kanban',
}
